accounts/urls.py
from django.urls import path
from .views import *

app_name = "account"

urlpatterns = [
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "post"
urlpatterns = [
    path('', views.post_index, name="index"),
    # post
    path('detail/<slug:slug>', views.post_detail, name='detail'),
    path('create/', views.post_create, name="create"),
    path('update/<int:id>/<slug:slug>', views.post_update, name="update"),
    path('delete/<int:id>/<slug:slug>', views.post_delete, name="delete"),
    # category
    path('categories/', views.category_list, name='category_list'),
    path('category/<int:id>/<slug:slug>', views.category, name='category'),
    path('create/category', views.add_category, name="add_category"),
    path('update/category/<int:id>/<slug:slug>',
         views.update_category, name="update_category"),
    path('delete/category/<int:id>/<slug:slug>',
         views.delete_category, name="delete_category"),
    # tag
    path('tags/', views.tag_list, name='tag_list'),
    path('tag/<int:id>/<slug:slug>', views.tag, name='tag'),
    path('create/tag', views.add_tag, name="add_tag"),
    path('update/tag/<int:id>/<slug:slug>',
         views.update_tag, name="update_tag"),
    path('delete/tag/<int:id>/<slug:slug>',
         views.delete_tag, name="delete_tag"),
]

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.index, name="index"),
    path('contact/', views.contact, name="contact"),
    path('delete/profile/<int:id>/', views.delete_profile, name="delete_profile"),
]

mySite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls'))
]

static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.utils.safestring import mark_safe
from django.urls import reverse

from ckeditor.fields import RichTextField

# Create your models here.


class Social(models.Model):
    name = models.CharField(max_length=200, blank=True)
    link = models.URLField(max_length=200, blank=True)

    def __str__(self):
        return self.name


class Experience(models.Model):
    title = models.CharField(max_length=200, blank=True)
    subTitle = models.CharField(max_length=200, blank=True)
    description = models.TextField(max_length=300, blank=True)
    date = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.title


class Education(models.Model):
    title = models.CharField(max_length=200, blank=True)
    subTitle = models.CharField(max_length=200, blank=True)
    description = models.TextField(max_length=300, blank=True)
    date = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.title


class Skills(models.Model):
    title = models.CharField(max_length=200, blank=True)
    workflow = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.title


class Interest(models.Model):
    content = RichTextField(max_length=300, blank=True)

    def __str__(self):
        return self.content[:100]


class AwardAndCertifica(models.Model):
    title = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.title


class Home(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False')
    )
    name = models.CharField(max_length=200)
    surName = models.CharField(max_length=200)
    email = models.EmailField(max_length=254)
    shortLament = RichTextField()
    description = RichTextField()
    links = models.ManyToManyField(Social, blank=True)
    experiences = models.ManyToManyField(Experience, blank=True)
    educations = models.ManyToManyField(Education, blank=True)
    skills = models.ManyToManyField(Skills, blank=True)
    interest = models.ManyToManyField(Interest, blank=True)
    awardsandcertificates = models.ManyToManyField(
        AwardAndCertifica, blank=True)
    image = models.ImageField(blank=True, upload_to='home/')
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def image_tag(self):
        if self.image:
            return mark_safe('<img src="{}" height="100"/>'.format(self.image.url))

    def get_delete_url(self):
        return reverse('home:delete_profile', kwargs={'id': self.id})

    image_tag.short_description = "Image"
    image_tag.allow_tags = True


class Contact(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed')
    )

    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=254)
    website = models.URLField(max_length=300)
    subject = models.CharField(max_length=255)
    message = models.TextField(max_length=255)
    ip = models.CharField(max_length=20)
    status = models.CharField(max_length=10, choices=STATUS, default="New")
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Contact Form Message"
        verbose_name_plural = "Contact Form Messages"


class Setting(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    icon = models.ImageField(blank=True, upload_to='settings/')
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

home/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = [
            'name',
            'email',
            'website',
            'subject',
            'message',
        ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your name'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'type': 'email', 'placeholder': 'Your email'}),
            'website': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Website'}),
            'subject': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Subject'}),
            'message': forms.Textarea(attrs={'class': 'form-control no-resize', 'rows': "4", 'placeholder': 'Please type what you want...'}),
        }

home/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.http.response import HttpResponseRedirect
from home.forms import ContactForm
from .models import *
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    context = {
        'settings': Setting.objects.filter(status="True").last(),
        'content': Home.objects.filter(status="True"),
        'links': Social.objects.all(),
        'experiences': Experience.objects.all(),
        'educations': Education.objects.all(),
        'skills': Skills.objects.all(),
        'awards': AwardAndCertifica.objects.all(),
    }
    return render(request, 'home/index.html', context)


@login_required()
def delete_profile(request, id):
    profile = get_object_or_404(Home, id=id)
    try:
        profile.delete()
        messages.success(request, "Profile deleted.")
    except:
        messages.error(request, "Profile not deleted.")

    return redirect('home:index')


def contact(request):
    form = ContactForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            contact = form.save()
            contact.ip = request.META.get('REMOTE_ADDR')
            url = request.META.get('HTTP_REFERER')
            contact.save()
            messages.success(request, 'Message sent.')
            return HttpResponseRedirect(url)
        else:
            messages.warning(request, 'Message could not be sent.')

    context = {'form': form,
               'content': Home.objects.filter(status="True"),
               }

    return render(request, 'home/contact.html', context)

templates/home/about.html
{% block content %}
<hr class="m-0" />
            {% if request.user.is_authenticated %}
                <div style="margin-left:5px;justify-content:space-between">
                    <a href="/admin/home/home/add/"class="btn btn-block btn-warning mt-3 mr-3">Create Profile</a>
                    {% for item in content %}
                    <a href="/admin/home/home/{{item.id}}/change/" class="btn btn-block btn-info mt-3">Update Profile</a>
                    <a href="{{item.get_delete_url}}"class="btn btn-block btn-danger mt-3">Delete Profile</a>
                    {% endfor %}
                    <a href="{% url 'admin:index' %}"class="btn btn-block btn-dark mt-3">Admin Page</a>
                    <a href="{% url 'account:logout' %}"class="btn btn-block btn-danger mt-3" style="margin-left:15px">Logout</a>
                    <hr>
                    <h5 class="mt-3">
                        Welcome
                        <span class="text-primary">{{request.user.get_full_name}} ({{request.user.username}})</span>
                    </h5>
                </div>
            {% else %}
                <div style="margin-left:5px;justify-content:space-between">
                    <a href="{% url 'account:login' %}"class="btn btn-block btn-success mt-3" style="margin-left:15px">Login</a>
                    <a href="https://github.com/alii76tt/django-personal-website"class="btn btn-block btn-light mt-3" style="margin-left:15px">Source Code</a>
                </div>
            {% endif %}
            <!-- About-->
            <section class="resume-section p-3 p-lg-5 d-flex d-column" id="about">
                <div class="resume-section-content">
                {% if content %}
                {% for item in content %}
                    <h1 class="mb-0">
                        {{item.name}}
                        <span class="text-primary">{{item.surName}}</span>
                    </h1>
                    <div class="subheading mb-5">
                        {{item.shortLament|safe}}
                        <a href="mailto:name@email.com">{{item.email}}</a>
                    </div>
                    <p class="lead mb-5">{{item.description|safe}}</p>
                    {% if links %}
                        <div class="social-icons">
                        {% for link in links %}
                            {% if link.name == "linkedin" %}
                            <a class="social-icon" href="{{link.link}}"><i class="fab fa-linkedin-in"></i></a>
                            {% elif link.name == "github" %}
                            <a class="social-icon" href="{{link.link}}"><i class="fab fa-github"></i></a>
                            {% elif link.name == "twitter"%}
                            <a class="social-icon" href="{{link.link}}"><i class="fab fa-twitter"></i></a>
                            {% elif link.name == "facebook"%}
                            <a class="social-icon" href="{{link.link}}"><i class="fab fa-facebook-f"></i></a>
                            {% elif link.name == "hackerrank"%}
                            <a class="social-icon" href="{{link.link}}"><i class="fab fa-hackerrank"></i></a>
                            {% endif %}
                        {% endfor %}    
                        </div>
                    {% endif %}
                </div>
                {% endfor %}
                {% else %}
                    <h2 class="mb-0">
                       About Not
                        <span class="text-primary">Found</span>
                    </h2>
                {% endif %}
            </section>
{% endblock content %}

templates/home/awards.html
<hr class="m-0" />
            <!-- Awards-->
            <section class="resume-section p-3 p-lg-5 d-flex d-column" id="awards">
                <div class="resume-section-content">
                    <h2 class="mb-5">Awards & Certifications</h2>
                    {% if content %}
                    {% for award in awards %}
                    <ul class="fa-ul mb-0">
                        <li>
                            <span class="fa-li"><i class="fas fa-trophy text-warning"></i></span>
                            {{award.title}}
                        </li>
                    </ul>
                    {% endfor %}
                    {% endif %}
                </div>
            </section>

templates/home/contact.html
{% extends 'base/base.html' %}
{% block content %}
{% include 'base/navbar.html' %}
<div class="container bootstrap snippets bootdey">
<div class="row ng-scope mt-5">
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-body mt-5">
            {% include 'base/message.html' %}
                <div class="h4 text-center">Contact Information</div>
                <div class="row pv-lg">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-8">
                        <form class="form-horizontal ng-pristine ng-valid" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="col-sm-2 control-label" name="name" for="inputContact1">Name</label>
                                <div class="col-sm-10">
                                    {{form.name}}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="inputContact2">Email</label>
                                <div class="col-sm-10">
                                    {{form.email}}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="inputContact3">Website</label>
                                <div class="col-sm-10">
                                    {{form.website}}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" name="name" for="inputContact4">Subject</label>
                                <div class="col-sm-10">
                                    {{form.subject}}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="inputContact5">Message</label>
                                <div class="col-sm-10">
                                    {{form.message}}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10 mt-5">
                                    <button class="btn btn-danger" type="submit">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>


{% endblock content %}

templates/home/education.html
<hr class="m-0" />
            <!-- Education-->
            <section class="resume-section p-3 p-lg-5 d-flex d-column" id="education">
                <div class="resume-section-content">
                    <h2 class="mb-5">Education</h2>
                    {% if content %}
                    {% for education in educations %}
                    <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
                        <div class="flex-grow-1">
                            <h3 class="mb-0">{{education.title}}</h3>
                            <div class="subheading mb-3">{{education.subTitle}}</div>
                            <div>{{education.description}}</div>
                        </div>
                        <div class="flex-shrink-0"><span class="text-primary">{{education.date}}</span></div>
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>
            </section>

templates/home/experience.html
<hr class="m-0" />
            <!-- Experience-->
            <section class="resume-section p-3 p-lg-5 d-flex d-column" id="experience">
                <div class="resume-section-content">
                    <h2 class="mb-5">Experience</h2>
                    {% if content %}
                    {% for experience in experiences %}
                    <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
                        <div class="flex-grow-1">
                            <h3 class="mb-0">{{experience.title}}</h3>
                            <div class="subheading mb-3">{{experience.subTitle}}</div>
                            <p>{{experience.description}}</p>
                        </div>
                        <div class="flex-shrink-0"><span class="text-primary">{{experience.date}}</span></div>
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>
            </section>

templates/home/index.html
{% extends 'base/base.html' %}

{% block title %} {{ settings.title }} {% endblock %}
{% block keywords %}{{ settings.keywords }}{% endblock %}
{% block description %}{{ settings.description }}{% endblock %}
{% block icon %}{{ settings.icon.url }}{% endblock %}

{% block content %}
{% include 'base/navbar.html' %}
  <div class="container-fluid p-0">

{% include 'home/about.html' %}
{% include 'home/experience.html' %}
{% include 'home/education.html' %}
{% include 'home/skills.html' %}
{% include 'home/interest.html' %}
{% include 'home/awards.html' %}
	</div>

{% endblock content %}

templates/home/interest.html
<hr class="m-0" />
            <!-- Interests-->
            <section class="resume-section p-3 p-lg-5 d-flex d-column" id="interests">
                <div class="resume-section-content">
                    <h2 class="mb-5">Interests</h2>
                    {% if content %}
                    {% for interest in interests %}
                    <p>{{interest.content}}</p>
                    {% endfor %}
                    {% endif %}
                </div>
            </section>

templates/home/skills.html
<hr class="m-0" />
<!-- Skills-->
            <section class="resume-section p-3 p-lg-5 d-flex d-column" id="skills">
                <div class="resume-section-content">
                    <h2 class="mb-5">Skills</h2>
                    <div class="subheading mb-3">Programming Languages & Tools</div>
                    {% if content %}
                    <ul class="list-inline dev-icons">
                    {% for skill in skills %}
                        {% if skill.title == 'html5' %}
                            <li class="list-inline-item text-primary"><i class="fab fa-html5"></i></li>
                        {% elif skill.title == 'css3' %}
                            <li class="list-inline-item text-primary"><i class="fab fa-css3-alt"></i></li>
                        {% elif skill.title == 'python' %}
                            <li class="list-inline-item text-primary"><i class="fab fa-python"></i></li>
                        {% elif skill.title == 'php' %}
                            <li class="list-inline-item text-primary"><i class="fab fa-php"></i></li>
                        {% elif skill.title == 'java' %}
                            <li class="list-inline-item text-primary"><i class="fab fa-java"></i></li>
                        {% elif skill.title == 'javascript' %}
                            <li class="list-inline-item text-primary"><i class="fab fa-js-square"></i></li>
                        {% elif skill.title == 'node' %}
                            <li class="list-inline-item text-primary"><i class="fab fa-node-js"></i></li>
                        {% elif skill.title == 'wordpress' %}
                            <li class="list-inline-item text-primary"><i class="fab fa-wordpress"></i></li>
                        {% endif %}
                    {% endfor %}
                    </ul>
                    <div class="subheading mb-3">Workflow</div>
                    {% for skill in skills %}
                    <ul class="fa-ul mb-0">
                        <li>
                            <span class="fa-li"><i class="fas fa-check text-primary"></i></span>
                            {{skill.workflow}}
                        </li>
                    </ul>
                    {% endfor %}
                    {% endif %}
                </div>
            </section>